                    ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"risk_db","t_risk_decision_order","%s",NOW(),NOW(),3);              ',
                        ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"decision_engine","login_user_info","%s",NOW(),NOW(),3);            ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"decision_engine","t_user","%s",NOW(),NOW(),3);                     ',
         ',
               ',
                       ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_urge_backup_mobile","%s",NOW(),NOW(),3);               ',
         ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_urge_case_call_arouse","%s",NOW(),NOW(),3);            ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_urge_case_info","%s",NOW(),NOW(),3);                   ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_wa_pool","%s",NOW(),NOW(),3);                          ',
              ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_wa_task_send_record","%s",NOW(),NOW(),3);              ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_wa_task_send_record","%s",NOW(),NOW(),3);              ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_wa_task_send_record_detail","%s",NOW(),NOW(),3);       ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_wa_task_send_record_detail","%s",NOW(),NOW(),3);       ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_wa_task_send_record_detail","%s",NOW(),NOW(),3);       ',
        ',

'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_sensitive_mobile","%s",NOW(),NOW(),3);                 ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_sys_user","%s",NOW(),NOW(),3);                         ',
              ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_urge_case_call_arouse","%s",NOW(),NOW(),3);            ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_urge_case_call_arouse","%s",NOW(),NOW(),3);            ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"urge_db","t_urge_case_info","%s",NOW(),NOW(),3);                   ',
                ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"credit_db","app_to_diff_app_cr","%s",NOW(),NOW(),3);               ',
'insert iNTO  data_masking_columns (rule_type,active,table_schema,table_name,column_name,create_time,sys_time,instance_id)  values (1,1,"credit_db","fl_bc_ll_ft_cc_app_to_dh_app_cr","%s",NOW(),NOW(),3);  ',]
