# Generated by Django 3.2.8 on 2021-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0002_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='rate',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
