# Generated by Django 3.2.8 on 2021-12-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0003_dog_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
