# Generated by Django 3.2.8 on 2021-12-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0005_auther_add_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phote', models.ImageField(upload_to='cars/')),
            ],
        ),
    ]
