# Generated by Django 3.2.8 on 2021-12-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bieke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
