# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
