# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='depart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Department'),
        ),
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.CharField(default='1.1.1.1', max_length=32),
        ),
    ]
